In [8]:
import numpy as np

A = np.array([[0, 1],[2, 3],[4, 5]])
B = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])

matrix = np.dot(A, B)

print(matrix)
print(matrix.max())

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
